# EDA 01 — Primeira passagem pelo dataset SRAG

## Objetivo

Realizar a primeira inspeção reproduzível do Parquet oficial do projeto, carregando somente as colunas necessárias.

Esta etapa verifica:

- acesso ao Parquet distribuído pela GitHub Release;
- versão e localização do arquivo;
- schema e colunas disponíveis;
- compatibilidade da lista de colunas da EDA;
- dimensões e consumo de memória;
- tipos de dados;
- período temporal;
- valores ausentes;
- cardinalidade;
- categorias observadas;
- possíveis duplicidades;
- possíveis variáveis posteriores à admissão hospitalar.

## Limites desta etapa

Este notebook não:

- remove registros;
- imputa valores;
- converte ausência em “não”;
- define a lista final de features;
- cria o alvo definitivo;
- realiza split de treino, validação e holdout;
- treina modelos;
- altera configurações ou gates.

As conclusões desta EDA são descritivas e não causais.

In [1]:
from pathlib import Path
import platform
import sys

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

from IPython.display import display


def encontrar_raiz_projeto() -> Path:
    """
    Localiza a raiz do projeto procurando pelas pastas src e configs.
    """
    pasta_atual = Path.cwd().resolve()

    for pasta in [pasta_atual, *pasta_atual.parents]:
        possui_src = (pasta / "src").is_dir()
        possui_configs = (pasta / "configs").is_dir()

        if possui_src and possui_configs:
            return pasta

    raise FileNotFoundError(
        "Não foi possível localizar a raiz do projeto."
    )


ROOT_DIR = encontrar_raiz_projeto()

if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))


from src.utils import config as C
from src.utils import env
from src.utils import storage


env.carregar_dotenv()

print(f"Raiz do projeto: {ROOT_DIR}")
print(f"Python: {sys.version.split()[0]}")
print(f"Sistema: {platform.system()} {platform.release()}")
print(f"pandas: {pd.__version__}")

Raiz do projeto: C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador
Python: 3.14.7
Sistema: Windows 11
pandas: 3.0.6

In [2]:
print(C.resumo())

print(f"Release configurada: {C.DATA_VERSION}")
print(f"Nome do arquivo: {C.PARQUET_NAME}")
print(f"Diretório de tabelas: {C.TABLES_DIR}")
print(f"Diretório de figuras: {C.FIGURES_DIR}")

ROOT_DIR          = C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador
DATA_DIR          = C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\data
RAW_DIR           = C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\data\raw
PROCESSED_DIR     = C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\data\processed
TREINO_DIR        = C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\data\treino
OUTPUTS_DIR       = C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\outputs
RUNS_DIR          = C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\outputs\runs
LOGS_DIR          = C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\logs
CONFIGS_DIR       = C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\configs
SUPERVISED_YAML   = C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\configs\supervised.yaml (ok)
PARQUET_NAME      = srag.parquet
DATA_VERSION      = dados-v1
GITHUB_REPO       = Ivan-S-Oliveira/Projeto_Integrador
HTTP_TIMEOUT      = 180
HTTP_TENTATIVAS   = 3
SEED              = 42
GITHUB_TOKEN?     = False
SRAG_PARQUET_URL  = https://s3.sa-east-1.amazonaws.com/ckan.saude.gov.br/SRAG/2023/INFLUD23-16-10-2023.parquet
SUPERVISED_SHA256 = 5ba1cb2b4189b5f045e2e7558b21a5ec88daf040f6074e42be5db19c014127b6

Release configurada: dados-v1
Nome do arquivo: srag.parquet
Diretório de tabelas: C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\outputs\tables
Diretório de figuras: C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\reports\figures

In [3]:
COLUNAS_ESTRUTURA = [
    "nu_notific",
    "dt_notific",
    "dt_sin_pri",
    "sem_pri",
    "hospital",
    "dt_interna",
]

COLUNAS_CANDIDATAS = [
    "cs_sexo",
    "nu_idade_n",
    "tp_idade",
    "cs_gestant",
    "ave_suino",
    "febre",
    "tosse",
    "garganta",
    "dispneia",
    "diarreia",
    "vomito",
    "outro_sin",
    "puerpera",
    "cardiopati",
    "hematologi",
    "sind_down",
    "hepatica",
    "asma",
    "diabetes",
    "neurologic",
    "pneumopati",
    "imunodepre",
    "renal",
    "obesidade",
    "obes_imc",
    "out_morbi",
    "tabag",
    "vacina",
    "dt_ut_dose",
    "mae_vac",
    "dt_vac_mae",
    "dt_doseuni",
    "dt_1_dose",
    "dt_2_dose",
    "out_anim",
    "dor_abd",
    "fadiga",
    "perd_olft",
    "perd_pala",
    "vacina_cov",
    "dose_1_cov",
    "dose_2_cov",
    "dose_ref",
    "dose_2ref",
    "dose_adic",
    "dos_re_bi",
]

COLUNAS_AUDITORIA = [
    "evolucao",
    "dt_evoluca",
    "dt_encerra",
    "dt_digita",
]

COLUNAS_EDA = list(
    dict.fromkeys(
        COLUNAS_ESTRUTURA
        + COLUNAS_CANDIDATAS
        + COLUNAS_AUDITORIA
    )
)

print(f"Colunas de estrutura: {len(COLUNAS_ESTRUTURA)}")
print(f"Colunas candidatas: {len(COLUNAS_CANDIDATAS)}")
print(f"Colunas de auditoria: {len(COLUNAS_AUDITORIA)}")
print(f"Total sem duplicidades: {len(COLUNAS_EDA)}")

Colunas de estrutura: 6
Colunas candidatas: 46
Colunas de auditoria: 4
Total sem duplicidades: 56

In [4]:
caminho_parquet = storage.get_parquet(force=False)

print(f"Arquivo: {caminho_parquet}")
print(f"Existe: {caminho_parquet.exists()}")
print(
    "Tamanho do arquivo: "
    f"{caminho_parquet.stat().st_size / 1024**2:,.2f} MB"
)

Arquivo: C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\data\processed\dados-v1\srag.parquet
Existe: True
Tamanho do arquivo: 236.40 MB

In [5]:
arquivo_parquet = pq.ParquetFile(caminho_parquet)

schema = arquivo_parquet.schema_arrow
colunas_disponiveis = schema.names

metadados_parquet = {
    "arquivo": caminho_parquet.name,
    "versao_dados": C.DATA_VERSION,
    "numero_linhas": arquivo_parquet.metadata.num_rows,
    "numero_colunas": arquivo_parquet.metadata.num_columns,
    "numero_row_groups": arquivo_parquet.metadata.num_row_groups,
}

display(
    pd.DataFrame(
        [metadados_parquet]
    )
)

        arquivo versao_dados  numero_linhas  numero_colunas  numero_row_groups
0  srag.parquet     dados-v1        4445191             194                  9

In [6]:
schema_df = pd.DataFrame(
    {
        "coluna": schema.names,
        "tipo_arrow": [
            str(campo.type)
            for campo in schema
        ],
    }
)

display(schema_df.head(20))
print(f"Total de campos no schema: {len(schema_df)}")

        coluna    tipo_arrow
0   nu_notific  large_string
1   dt_notific  large_string
2      sem_not  large_string
3   dt_sin_pri  large_string
4      sem_pri  large_string
5    sg_uf_not  large_string
6   id_regiona  large_string
7   co_regiona  large_string
8   id_municip  large_string
9   co_mun_not  large_string
10     cs_sexo  large_string
11     dt_nasc  large_string
12  nu_idade_n  large_string
13    tp_idade  large_string
14   cod_idade  large_string
15  cs_gestant  large_string
16     cs_raca  large_string
17   cs_etinia  large_string
18  cs_escol_n  large_string
19     id_pais  large_string

Total de campos no schema: 194

In [7]:
conjunto_colunas_disponiveis = set(colunas_disponiveis)

status_colunas = pd.DataFrame(
    {
        "coluna": COLUNAS_EDA,
        "grupo": (
            ["estrutura"] * len(COLUNAS_ESTRUTURA)
            + ["candidata"] * len(COLUNAS_CANDIDATAS)
            + ["auditoria"] * len(COLUNAS_AUDITORIA)
        ),
    }
)

status_colunas["existe_no_parquet"] = (
    status_colunas["coluna"]
    .isin(conjunto_colunas_disponiveis)
)

display(status_colunas)

colunas_ausentes = status_colunas.loc[
    ~status_colunas["existe_no_parquet"],
    "coluna",
].tolist()

if colunas_ausentes:
    print("Colunas ausentes:")
    for coluna in colunas_ausentes:
        print(f"- {coluna}")
else:
    print("Todas as colunas solicitadas existem no Parquet.")

        coluna      grupo  existe_no_parquet
0   nu_notific  estrutura               True
1   dt_notific  estrutura               True
2   dt_sin_pri  estrutura               True
3      sem_pri  estrutura               True
4     hospital  estrutura               True
5   dt_interna  estrutura               True
6      cs_sexo  candidata               True
7   nu_idade_n  candidata               True
8     tp_idade  candidata               True
9   cs_gestant  candidata               True
10   ave_suino  candidata               True
11       febre  candidata               True
12       tosse  candidata               True
13    garganta  candidata               True
14    dispneia  candidata               True
15    diarreia  candidata               True
16      vomito  candidata               True
17   outro_sin  candidata               True
18    puerpera  candidata               True
19  cardiopati  candidata               True
20  hematologi  candidata               True
21   sind_down  candidata               True
22    hepatica  candidata               True
23        asma  candidata               True
24    diabetes  candidata               True
25  neurologic  candidata               True
26  pneumopati  candidata               True
27  imunodepre  candidata               True
28       renal  candidata               True
29   obesidade  candidata               True
30    obes_imc  candidata               True
31   out_morbi  candidata               True
32       tabag  candidata               True
33      vacina  candidata               True
34  dt_ut_dose  candidata               True
35     mae_vac  candidata               True
36  dt_vac_mae  candidata               True
37  dt_doseuni  candidata               True
38   dt_1_dose  candidata               True
39   dt_2_dose  candidata               True
40    out_anim  candidata               True
41     dor_abd  candidata               True
42      fadiga  candidata               True
43   perd_olft  candidata               True
44   perd_pala  candidata               True
45  vacina_cov  candidata               True
46  dose_1_cov  candidata               True
47  dose_2_cov  candidata               True
48    dose_ref  candidata               True
49   dose_2ref  candidata               True
50   dose_adic  candidata               True
51   dos_re_bi  candidata               True
52    evolucao  auditoria               True
53  dt_evoluca  auditoria               True
54  dt_encerra  auditoria               True
55   dt_digita  auditoria               True

Todas as colunas solicitadas existem no Parquet.

In [9]:
if colunas_ausentes:
    raise ValueError(
        "A leitura foi interrompida porque existem "
        "colunas ausentes no Parquet: "
        f"{colunas_ausentes}"
    )

print("Validação concluída. A leitura pode continuar.")

Validação concluída. A leitura pode continuar.

In [10]:
df = storage.read_srag(
    columns=COLUNAS_EDA,
)

print(f"Linhas carregadas: {df.shape[0]:,}")
print(f"Colunas carregadas: {df.shape[1]:,}")

display(df.head())

Linhas carregadas: 4,445,191
Colunas carregadas: 56

,nu_notific,dt_notific,dt_sin_pri,sem_pri,hospital,dt_interna,cs_sexo,nu_idade_n,tp_idade,cs_gestant,...,dose_1_cov,dose_2_cov,dose_ref,dose_2ref,dose_adic,dos_re_bi,evolucao,dt_evoluca,dt_encerra,dt_digita
0,315478195042,2018-12-30,2019-01-06,2,1.0,2019-01-06,M,30,3,6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,2019-01-25,2019-02-15,2019-03-14
1,315478195276,2018-12-30,2019-01-01,1,1.0,2019-01-01,F,7,2,6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,2019-03-05,2019-01-21,<NA>
2,315478207219,2018-12-30,2018-12-31,1,1.0,2019-01-02,M,1,3,6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,2019-02-12,2019-05-31,<NA>
3,315478211086,2018-12-30,2019-01-07,2,1.0,2019-01-10,F,5,2,6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,2019-01-29,2019-02-04,<NA>
4,315478212765,2018-12-30,2019-01-06,2,1.0,2019-01-13,F,3,2,6,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,2019-01-13,2019-05-21,<NA>

In [11]:
if df.empty:
    raise ValueError(
        "O DataFrame foi carregado sem registros."
    )

if list(df.columns) != COLUNAS_EDA:
    print(
        "Atenção: a ordem das colunas carregadas "
        "difere da lista solicitada."
    )

print(f"Dimensão: {df.shape}")
print(f"Índice único: {df.index.is_unique}")
print(f"Quantidade de linhas: {len(df):,}")
print(f"Quantidade de colunas: {df.shape[1]:,}")

Dimensão: (4445191, 56)
Índice único: True
Quantidade de linhas: 4,445,191
Quantidade de colunas: 56

In [12]:
tipos_memoria = pd.DataFrame(
    {
        "coluna": df.columns,
        "tipo_pandas": [
            str(df[coluna].dtype)
            for coluna in df.columns
        ],
        "memoria_mb": [
            df[coluna].memory_usage(deep=True) / 1024**2
            for coluna in df.columns
        ],
    }
)

tipos_memoria = tipos_memoria.sort_values(
    "memoria_mb",
    ascending=False,
).reset_index(drop=True)

memoria_total_mb = (
    df.memory_usage(deep=True).sum()
    / 1024**2
)

print(f"Memória total: {memoria_total_mb:,.2f} MB")
display(tipos_memoria)

Memória total: 2,483.20 MB

        coluna tipo_pandas  memoria_mb
0   nu_notific      string   87.624321
1   dt_notific      string   76.306887
2   dt_sin_pri      string   76.306887
3    dt_digita      string   76.265653
4   dt_interna      string   74.397500
5   dt_encerra      string   73.948575
6   dt_evoluca      string   71.059276
7     hospital      string   46.835349
8     evolucao      string   46.261359
9        tosse      string   45.715399
10    dispneia      string   45.577074
11       febre      string   45.226576
12  dose_1_cov      string   45.205373
13   ave_suino      string   44.979572
14    garganta      string   43.645655
15    diarreia      string   43.501983
16   outro_sin      string   43.501645
17  dose_2_cov      string   43.497790
18      vomito      string   43.444433
19  vacina_cov      string   42.780985
20      fadiga      string   42.549800
21   perd_olft      string   42.232472
22   perd_pala      string   42.223426
23     dor_abd      string   42.209023
24     sem_pri      string   41.702918
25  nu_idade_n      string   41.638844
26      vacina      string   41.096576
27   out_morbi      string   39.257419
28  cardiopati      string   39.119510
29    diabetes      string   38.813737
30   obesidade      string   38.603640
31  neurologic      string   38.583104
32        asma      string   38.576149
33  imunodepre      string   38.518053
34    dose_ref      string   38.495645
35  pneumopati      string   38.268283
36       renal      string   38.221004
37  hematologi      string   38.161978
38    tp_idade      string   38.153506
39     cs_sexo      string   38.153506
40  cs_gestant      string   38.153506
41   sind_down      string   38.149078
42    hepatica      string   38.146891
43    puerpera      string   38.139876
44  dt_ut_dose      string   37.715230
45   dose_2ref      string   36.039618
46   dos_re_bi      string   35.278006
47     mae_vac      string   34.682961
48    obes_imc      string   34.647970
49   dose_adic      string   34.614934
50   dt_1_dose      string   34.530049
51  dt_doseuni      string   34.528689
52   dt_2_dose      string   34.502313
53  dt_vac_mae      string   34.492832
54    out_anim      string   34.483479
55       tabag      string   34.444174

In [13]:
COLUNAS_DATA = [
    "dt_notific",
    "dt_sin_pri",
    "dt_interna",
    "dt_ut_dose",
    "dt_vac_mae",
    "dt_doseuni",
    "dt_1_dose",
    "dt_2_dose",
    "dt_evoluca",
    "dt_encerra",
    "dt_digita",
]

COLUNAS_DATA_EXISTENTES = [
    coluna
    for coluna in COLUNAS_DATA
    if coluna in df.columns
]

datas_convertidas = pd.DataFrame(
    {
        coluna: pd.to_datetime(
            df[coluna],
            errors="coerce",
        )
        for coluna in COLUNAS_DATA_EXISTENTES
    },
    index=df.index,
)

resumo_datas = pd.DataFrame(
    {
        "coluna": COLUNAS_DATA_EXISTENTES,
        "data_minima": [
            datas_convertidas[coluna].min()
            for coluna in COLUNAS_DATA_EXISTENTES
        ],
        "data_maxima": [
            datas_convertidas[coluna].max()
            for coluna in COLUNAS_DATA_EXISTENTES
        ],
        "validas": [
            datas_convertidas[coluna].notna().sum()
            for coluna in COLUNAS_DATA_EXISTENTES
        ],
        "invalidas_ou_ausentes": [
            datas_convertidas[coluna].isna().sum()
            for coluna in COLUNAS_DATA_EXISTENTES
        ],
    }
)

display(resumo_datas)

        coluna data_minima data_maxima  validas  invalidas_ou_ausentes
0   dt_notific  2017-12-31  2025-12-28  4445191                      0
1   dt_sin_pri  2018-12-30  2026-01-03  4445191                      0
2   dt_interna  2009-09-04  2224-08-10  4135245                 309946
3   dt_ut_dose  2009-03-02  2026-01-29   342997                4102194
4   dt_vac_mae  2000-05-09  2025-12-10     5104                4440087
5   dt_doseuni  2013-04-25  2026-01-27     8863                4436328
6    dt_1_dose  2012-08-06  2026-01-29     9001                4436190
7    dt_2_dose  2012-09-14  2026-02-06     6098                4439093
8   dt_evoluca  2019-01-01  2026-02-26  3839374                 605817
9   dt_encerra  2019-01-05  2026-02-28  4142339                 302852
10   dt_digita  2019-01-18  2026-02-28  4428367                  16824

In [14]:
if "dt_notific" not in datas_convertidas.columns:
    raise KeyError(
        "A coluna dt_notific não está disponível "
        "para avaliar o período temporal."
    )

ano_notificacao = (
    datas_convertidas["dt_notific"]
    .dt.year
    .rename("ano_notificacao")
)

volume_por_ano = (
    ano_notificacao
    .value_counts(dropna=False)
    .sort_index()
    .rename_axis("ano_notificacao")
    .reset_index(name="quantidade_registros")
)

volume_por_ano["percentual"] = (
    volume_por_ano["quantidade_registros"]
    / len(df)
    * 100
)

display(volume_por_ano)

   ano_notificacao  quantidade_registros  percentual
0             2017                     3    0.000067
1             2018                 48637    1.094149
2             2019               1148795   25.843546
3             2020               1773883   39.905664
4             2021                582657   13.107581
5             2023                552902   12.438206
6             2024                334220    7.518687
7             2025                  4094    0.092100

In [15]:
memoria_mb = (
    df.memory_usage(deep=True).sum()
    / 1024**2
)

print(f"Memória total utilizada: {memoria_mb:,.2f} MB")

Memória total utilizada: 2,483.20 MB

In [25]:
memoria_colunas = (
    df.memory_usage(deep=True)
    .div(1024**2)
    .rename("memoria_mb")
    .sort_values(ascending=False)
    .reset_index()
    .rename(columns={"index": "coluna"})
)

display(memoria_colunas)

        coluna  memoria_mb
0   nu_notific   87.624195
1   dt_sin_pri   76.306761
2   dt_notific   76.306761
3    dt_digita   76.265527
4   dt_interna   74.397374
5   dt_encerra   73.948449
6   dt_evoluca   71.059150
7     hospital   46.835223
8     evolucao   46.261233
9        tosse   45.715273
10    dispneia   45.576948
11       febre   45.226450
12  dose_1_cov   45.205247
13   ave_suino   44.979446
14    garganta   43.645529
15    diarreia   43.501857
16   outro_sin   43.501519
17  dose_2_cov   43.497664
18      vomito   43.444307
19  vacina_cov   42.780859
20      fadiga   42.549674
21   perd_olft   42.232347
22   perd_pala   42.223300
23     dor_abd   42.208898
24     sem_pri   41.702792
25  nu_idade_n   41.638718
26      vacina   41.096450
27   out_morbi   39.257293
28  cardiopati   39.119384
29    diabetes   38.813611
30   obesidade   38.603514
31  neurologic   38.582978
32        asma   38.576023
33  imunodepre   38.517927
34    dose_ref   38.495519
35  pneumopati   38.268157
36       renal   38.220878
37  hematologi   38.161852
38    tp_idade   38.153380
39  cs_gestant   38.153380
40     cs_sexo   38.153380
41   sind_down   38.148952
42    hepatica   38.146765
43    puerpera   38.139750
44  dt_ut_dose   37.715104
45   dose_2ref   36.039493
46   dos_re_bi   35.277880
47     mae_vac   34.682835
48    obes_imc   34.647844
49   dose_adic   34.614808
50   dt_1_dose   34.529923
51  dt_doseuni   34.528563
52   dt_2_dose   34.502187
53  dt_vac_mae   34.492706
54    out_anim   34.483353
55       tabag   34.444048
56       Index    0.000126

In [16]:
ausencias = pd.DataFrame(
    {
        "coluna": df.columns,
        "quantidade_ausente": [
            df[coluna].isna().sum()
            for coluna in df.columns
        ],
        "quantidade_preenchida": [
            df[coluna].notna().sum()
            for coluna in df.columns
        ],
    }
)

ausencias["percentual_ausente"] = (
    ausencias["quantidade_ausente"]
    / len(df)
    * 100
)

ausencias["percentual_preenchido"] = (
    ausencias["quantidade_preenchida"]
    / len(df)
    * 100
)

ausencias = ausencias.sort_values(
    "percentual_ausente",
    ascending=False,
).reset_index(drop=True)

display(ausencias)

,coluna,quantidade_ausente,quantidade_preenchida,percentual_ausente,percentual_preenchido
0,tabag,4445187,4,99.999910,0.000090
1,out_anim,4440432,4759,99.892940,0.107060
2,dt_vac_mae,4440084,5107,99.885112,0.114888
3,dt_2_dose,4439090,6101,99.862751,0.137249
4,dt_doseuni,4436325,8866,99.800549,0.199451
5,dt_1_dose,4436187,9004,99.797444,0.202556
6,dose_adic,4427283,17908,99.597138,0.402862
7,obes_imc,4391362,53829,98.789051,1.210949
8,dos_re_bi,4357754,87437,98.032998,1.967002
9,mae_vac,4349582,95609,97.849159,2.150841
10,dose_2ref,4277894,167297,96.236450,3.763550
11,dt_ut_dose,4102190,343001,92.283774,7.716226
12,dose_ref,4020361,424830,90.442930,9.557070
13,dose_2_cov,3495848,949343,78.643370,21.356630
14,dose_1_cov,3316795,1128396,74.615354,25.384646
15,puerpera,2905948,1539243,65.372849,34.627151
16,hepatica,2903086,1542105,65.308465,34.691535
17,sind_down,2902677,1542514,65.299264,34.700736
18,hematologi,2897181,1548010,65.175625,34.824375
19,imunodepre,2877106,1568085,64.724013,35.275987
20,renal,2871482,1573709,64.597494,35.402506
21,asma,2855341,1589850,64.234383,35.765617
22,pneumopati,2852135,1593056,64.162260,35.837740
23,neurologic,2852104,1593087,64.161562,35.838438
24,obesidade,2845331,1599860,64.009196,35.990804
25,diabetes,2620665,1824526,58.955060,41.044940
26,out_morbi,2596800,1848391,58.418187,41.581813
27,cardiopati,2490943,1954248,56.036805,43.963195
28,dor_abd,1731171,2714020,38.944806,61.055194
29,perd_pala,1726137,2719054,38.831560,61.168440
30,perd_olft,1722975,2722216,38.760427,61.239573
31,fadiga,1612061,2833130,36.265281,63.734719
32,vacina_cov,1531256,2913935,34.447474,65.552526
33,vomito,1299364,3145827,29.230780,70.769220
34,outro_sin,1279367,3165824,28.780923,71.219077
35,diarreia,1279249,3165942,28.778268,71.221732
36,garganta,1229032,3216159,27.648576,72.351424
37,vacina,1184651,3260540,26.650171,73.349829
38,ave_suino,762794,3682397,17.159983,82.840017
39,febre,676460,3768731,15.217794,84.782206
40,dt_evoluca,605815,3839376,13.628548,86.371452
41,dispneia,553952,3891239,12.461827,87.538173
42,tosse,505604,3939587,11.374179,88.625821
43,evolucao,314777,4130414,7.081293,92.918707
44,dt_encerra,302850,4142341,6.812981,93.187019
45,dt_interna,291267,4153924,6.552407,93.447593
46,hospital,114153,4331038,2.568011,97.431989
47,dt_digita,16821,4428370,0.378409,99.621591
48,tp_idade,0,4445191,0.000000,100.000000
49,cs_gestant,0,4445191,0.000000,100.000000
50,nu_notific,0,4445191,0.000000,100.000000
51,dt_notific,0,4445191,0.000000,100.000000
52,sem_pri,0,4445191,0.000000,100.000000
53,dt_sin_pri,0,4445191,0.000000,100.000000
54,cs_sexo,0,4445191,0.000000,100.000000
55,nu_idade_n,0,4445191,0.000000,100.000000

In [17]:
df_temporal = df.copy()

df_temporal["ano_notificacao"] = ano_notificacao

preenchimento_por_ano = (
    df_temporal
    .groupby("ano_notificacao", dropna=False)
    [COLUNAS_EDA]
    .apply(lambda grupo: grupo.notna().mean() * 100)
    .reset_index()
)

display(preenchimento_por_ano)

,ano_notificacao,nu_notific,dt_notific,dt_sin_pri,sem_pri,hospital,dt_interna,cs_sexo,nu_idade_n,tp_idade,...,dose_1_cov,dose_2_cov,dose_ref,dose_2ref,dose_adic,dos_re_bi,evolucao,dt_evoluca,dt_encerra,dt_digita
0,2017,100.0,100.0,100.0,100.0,100.000000,100.000000,100.0,100.0,100.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,100.000000,100.000000,100.000000,66.666667
1,2018,100.0,100.0,100.0,100.0,99.438699,97.316858,100.0,100.0,100.0,...,0.096634,0.071962,0.024673,0.008224,0.002056,0.006168,94.189609,84.080021,96.418365,65.421387
2,2019,100.0,100.0,100.0,100.0,97.624467,92.570650,100.0,100.0,100.0,...,2.152952,2.026471,1.185677,0.472321,0.036560,0.106198,93.641076,87.272316,94.055597,100.000000
3,2020,100.0,100.0,100.0,100.0,97.372600,93.659616,100.0,100.0,100.0,...,20.068065,13.423320,1.929891,0.467393,0.029652,0.087435,91.926751,85.794610,92.464497,99.999887
4,2021,100.0,100.0,100.0,100.0,96.706467,92.862868,100.0,100.0,100.0,...,56.679144,52.851163,27.512585,4.705170,0.077576,0.151547,91.922006,85.642496,91.870689,100.000000
5,2023,100.0,100.0,100.0,100.0,97.518909,94.275116,100.0,100.0,100.0,...,48.126069,43.851894,25.623709,14.890704,1.850961,8.463525,94.711178,88.019938,94.218686,100.000000
6,2024,100.0,100.0,100.0,100.0,97.919335,94.476991,100.0,100.0,100.0,...,44.641853,40.562504,22.127042,12.935492,1.848782,10.914368,94.387230,85.392257,94.256478,100.000000
7,2025,100.0,100.0,100.0,100.0,97.044455,89.106009,100.0,100.0,100.0,...,51.172447,47.557401,25.207621,14.582316,2.344895,12.383977,84.807035,71.787982,84.831461,100.000000

In [18]:
cardinalidade = pd.DataFrame(
    {
        "coluna": df.columns,
        "valores_distintos_sem_na": [
            df[coluna].nunique(dropna=True)
            for coluna in df.columns
        ],
        "valores_distintos_com_na": [
            df[coluna].nunique(dropna=False)
            for coluna in df.columns
        ],
    }
)

cardinalidade = cardinalidade.sort_values(
    "valores_distintos_com_na",
    ascending=False,
).reset_index(drop=True)

display(cardinalidade)

        coluna  valores_distintos_sem_na  valores_distintos_com_na
0   nu_notific                   4445169                   4445169
1   dt_interna                      3920                      3921
2   dt_ut_dose                      2838                      2839
3   dt_evoluca                      2616                      2617
4   dt_encerra                      2611                      2612
5   dt_sin_pri                      2562                      2562
6    dt_digita                      2554                      2555
7   dose_1_cov                      1896                      1897
8   dose_2_cov                      1818                      1819
9   dt_vac_mae                      1579                      1580
10   dt_1_dose                      1567                      1568
11   dt_2_dose                      1472                      1473
12  dt_doseuni                      1313                      1314
13    dose_ref                      1093                      1094
14    obes_imc                      1086                      1087
15   dos_re_bi                       744                       745
16   dose_adic                       734                       735
17   dose_2ref                       725                       726
18    out_anim                       528                       529
19  nu_idade_n                       139                       139
20     sem_pri                        53                        53
21      vacina                        10                        11
22   sind_down                         8                         9
23  dt_notific                         9                         9
24  hematologi                         8                         9
25    diabetes                         8                         9
26  pneumopati                         8                         9
27  neurologic                         8                         9
28       renal                         8                         9
29     mae_vac                         8                         9
30        asma                         8                         9
31    puerpera                         8                         9
32    hepatica                         8                         9
33  imunodepre                         7                         8
34   obesidade                         7                         8
35  cardiopati                         7                         8
36  cs_gestant                         8                         8
37   out_morbi                         7                         8
38   ave_suino                         4                         5
39      fadiga                         4                         5
40    evolucao                         4                         5
41   perd_olft                         4                         5
42     dor_abd                         4                         5
43       tosse                         3                         4
44    hospital                         3                         4
45    garganta                         3                         4
46    diarreia                         3                         4
47      vomito                         3                         4
48    dispneia                         3                         4
49   perd_pala                         3                         4
50       febre                         3                         4
51   outro_sin                         3                         4
52  vacina_cov                         3                         4
53     cs_sexo                         3                         3
54    tp_idade                         3                         3
55       tabag                         2                         3

In [19]:
LIMITE_CARDINALIDADE = 30

colunas_categoricas_baixas = cardinalidade.loc[
    cardinalidade["valores_distintos_com_na"]
    <= LIMITE_CARDINALIDADE,
    "coluna",
].tolist()

frequencias_categoricas = []

for coluna in colunas_categoricas_baixas:
    frequencia = (
        df[coluna]
        .value_counts(
            dropna=False,
            normalize=False,
        )
        .rename("quantidade")
        .reset_index()
        .rename(columns={"index": "valor"})
    )

    frequencia["coluna"] = coluna
    frequencia["percentual"] = (
        frequencia["quantidade"]
        / len(df)
        * 100
    )

    frequencias_categoricas.append(frequencia)

frequencias_categoricas_df = pd.concat(
    frequencias_categoricas,
    ignore_index=True,
)

display(frequencias_categoricas_df.head(100))

,vacina,quantidade,coluna,percentual,sind_down,dt_notific,hematologi,diabetes,pneumopati,neurologic,...,diarreia,vomito,dispneia,perd_pala,febre,outro_sin,vacina_cov,cs_sexo,tp_idade,tabag
0,<NA>,1184651,vacina,26.650171,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,2.0,903812,vacina,20.332355,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,9,664537,vacina,14.949571,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,9.0,641839,vacina,14.438952,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,2,546575,vacina,12.295872,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,<NA>,22450,puerpera,0.50504,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
96,<NA>,11230,puerpera,0.252633,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
97,<NA>,9048,puerpera,0.203546,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
98,<NA>,3593,puerpera,0.080829,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
99,<NA>,1,puerpera,0.000022,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

In [20]:
if "nu_notific" in df.columns:
    identificadores_preenchidos = df["nu_notific"].notna().sum()

    identificadores_duplicados = (
        df.loc[
            df["nu_notific"].notna(),
            "nu_notific",
        ]
        .duplicated(keep=False)
        .sum()
    )

    resumo_identificador = pd.DataFrame(
        {
            "metrica": [
                "linhas_totais",
                "identificadores_preenchidos",
                "linhas_com_identificador_duplicado",
            ],
            "valor": [
                len(df),
                identificadores_preenchidos,
                identificadores_duplicados,
            ],
        }
    )

    display(resumo_identificador)
else:
    print(
        "nu_notific não foi carregada. "
        "A auditoria de identificador não será executada."
    )

                              metrica    valor
0                       linhas_totais  4445191
1         identificadores_preenchidos  4445191
2  linhas_com_identificador_duplicado       44

In [21]:
COLUNAS_POTENCIALMENTE_POS_ADMISSAO = [
    "evolucao",
    "dt_evoluca",
    "dt_encerra",
    "dt_digita",
]

auditoria_vazamento = pd.DataFrame(
    {
        "coluna": COLUNAS_POTENCIALMENTE_POS_ADMISSAO,
        "existe_no_dataframe": [
            coluna in df.columns
            for coluna in COLUNAS_POTENCIALMENTE_POS_ADMISSAO
        ],
        "uso_nesta_eda": "auditoria",
        "candidata_feature": False,
        "justificativa": (
            "Desfecho ou informação potencialmente "
            "posterior à admissão hospitalar."
        ),
    }
)

display(auditoria_vazamento)

,coluna,existe_no_dataframe,uso_nesta_eda,candidata_feature,justificativa
0,evolucao,True,auditoria,False,Desfecho ou informação potencialmente posterio...
1,dt_evoluca,True,auditoria,False,Desfecho ou informação potencialmente posterio...
2,dt_encerra,True,auditoria,False,Desfecho ou informação potencialmente posterio...
3,dt_digita,True,auditoria,False,Desfecho ou informação potencialmente posterio...

In [22]:
resumo_primeira_passagem = pd.DataFrame(
    {
        "metrica": [
            "versao_dados",
            "arquivo",
            "linhas_parquet",
            "colunas_parquet",
            "linhas_carregadas",
            "colunas_carregadas",
            "memoria_mb",
            "data_minima_notificacao",
            "data_maxima_notificacao",
            "colunas_ausentes",
        ],
        "valor": [
            C.DATA_VERSION,
            caminho_parquet.name,
            arquivo_parquet.metadata.num_rows,
            arquivo_parquet.metadata.num_columns,
            df.shape[0],
            df.shape[1],
            round(memoria_total_mb, 2),
            datas_convertidas["dt_notific"].min(),
            datas_convertidas["dt_notific"].max(),
            len(colunas_ausentes),
        ],
    }
)

display(resumo_primeira_passagem)

                   metrica                valor
0             versao_dados             dados-v1
1                  arquivo         srag.parquet
2           linhas_parquet              4445191
3          colunas_parquet                  194
4        linhas_carregadas              4445191
5       colunas_carregadas                   56
6               memoria_mb               2483.2
7  data_minima_notificacao  2017-12-31 00:00:00
8  data_maxima_notificacao  2025-12-28 00:00:00
9         colunas_ausentes                    0

In [24]:
C.TABLES_DIR.mkdir(
parents=True,
exist_ok=True,
)

print(f"Tabelas serão salvas em: {C.TABLES_DIR}")

Tabelas serão salvas em: C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\outputs\tables

In [25]:
tabelas_exportacao = {
    "eda_01_resumo_primeira_passagem.csv": (
        resumo_primeira_passagem
    ),
    "eda_01_status_colunas.csv": (
        status_colunas
    ),
    "eda_01_tipos_memoria.csv": (
        tipos_memoria
    ),
    "eda_01_resumo_datas.csv": (
        resumo_datas
    ),
    "eda_01_volume_por_ano.csv": (
        volume_por_ano
    ),
    "eda_01_ausencias.csv": (
        ausencias
    ),
    "eda_01_preenchimento_por_ano.csv": (
        preenchimento_por_ano
    ),
    "eda_01_cardinalidade.csv": (
        cardinalidade
    ),
    "eda_01_frequencias_categoricas.csv": (
        frequencias_categoricas_df
    ),
    "eda_01_auditoria_vazamento.csv": (
        auditoria_vazamento
    ),
}

for nome_arquivo, tabela in tabelas_exportacao.items():
    caminho_saida = C.TABLES_DIR / nome_arquivo

    tabela.to_csv(
        caminho_saida,
        index=False,
        encoding="utf-8-sig",
    )

    print(f"Salvo: {caminho_saida}")

Salvo: C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\outputs\tables\eda_01_resumo_primeira_passagem.csv
Salvo: C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\outputs\tables\eda_01_status_colunas.csv
Salvo: C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\outputs\tables\eda_01_tipos_memoria.csv
Salvo: C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\outputs\tables\eda_01_resumo_datas.csv
Salvo: C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\outputs\tables\eda_01_volume_por_ano.csv
Salvo: C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\outputs\tables\eda_01_ausencias.csv
Salvo: C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\outputs\tables\eda_01_preenchimento_por_ano.csv
Salvo: C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\outputs\tables\eda_01_cardinalidade.csv
Salvo: C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\outputs\tables\eda_01_frequencias_categoricas.csv
Salvo: C:\Users\olivem85\OneDrive - Pfizer\Documents\GitHub\Projeto_Integrador\outputs\tables\eda_01_auditoria_vazamento.csv

## Decisões pendentes após a primeira passagem

### Schema

- Confirmar o significado das colunas ausentes ou com nomes diferentes.
- Alinhar os nomes físicos do Parquet aos nomes documentados.
- Verificar especificamente `dt_evoluca` versus `dt_evolucao`.
- Verificar especificamente `dt_encerra` versus `dt_encerramento`.

### Unidade de análise

- Confirmar se `nu_notific` identifica de forma adequada uma notificação.
- Investigar duplicidades antes de definir qualquer remoção.
- Não interpretar registros automaticamente como pessoas únicas.

### Ausências

- Distinguir vazio, ignorado, não se aplica, campo inexistente e resposta negativa.
- Não converter ausência em zero ou “não” sem regra documentada.
- Comparar preenchimento entre anos antes de excluir variáveis.

### Datas

- Investigar datas inválidas e sequências temporais impossíveis.
- Definir o período elegível do estudo.
- Identificar anos incompletos.
- Levar a cobertura temporal para a decisão do Gate G2.

### Features e vazamento

- A presença de uma coluna na EDA não significa aprovação como feature.
- `evolucao`, `dt_evoluca`, `dt_encerra` e `dt_digita` permanecem apenas para auditoria.
- Revisar todas as colunas conforme a disponibilidade plausível até a admissão.
- Atualizar a lista de variáveis proibidas somente após decisão formal.

### Próxima etapa

- Executar uma EDA descritiva por ano e por grupo.
- Comparar frequências, preenchimento e categorias entre períodos.
- Criar um relatório de hipóteses e riscos.
- Não usar o holdout para escolher features, tratamentos ou modelos.

In [26]:
verificacoes_finais = {
    "dataframe_nao_vazio": not df.empty,
    "colunas_solicitadas_presentes": not colunas_ausentes,
    "dt_notific_disponivel": "dt_notific" in df.columns,
    "evolucao_apenas_auditoria": (
        "evolucao" in COLUNAS_AUDITORIA
        and "evolucao" not in COLUNAS_CANDIDATAS
    ),
    "diretorio_tabelas_existe": C.TABLES_DIR.exists(),
}

verificacoes_finais_df = pd.DataFrame(
    {
        "verificacao": verificacoes_finais.keys(),
        "resultado": verificacoes_finais.values(),
    }
)

display(verificacoes_finais_df)

if not all(verificacoes_finais.values()):
    raise RuntimeError(
        "Uma ou mais verificações finais falharam."
    )

print("Primeira passagem concluída com sucesso.")

                     verificacao  resultado
0            dataframe_nao_vazio       True
1  colunas_solicitadas_presentes       True
2          dt_notific_disponivel       True
3      evolucao_apenas_auditoria       True
4       diretorio_tabelas_existe       True

Primeira passagem concluída com sucesso.